import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Admin from "@/demo/Admin";

import { Toaster } from "react-hot-toast";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <header>
          <Header> </Header>
        </header>
        <main>  {children}</main>
        <Footer />
        <Toaster  position="bottom-center"
  />
      </body>
    </html>
  );
}
