import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Home/header";


import { Toaster } from "react-hot-toast";
import { Footer } from "@/components/Home/footer";
import { SessionProvider, SessionProviderProps } from "next-auth/react";
import { PageProps } from "../../.next/types/app/layout";
import { AppProps } from "next/app";
import Burger from "@/components/Home/burger";
import { Hamburger } from "@/components/Home/hamburger";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, session
}: Readonly<{
  children: React.ReactNode, session: AppProps & never;
}>) {
  return (
    <html lang="en">
      <body >
      
        {/* <header> */}
        {/* <Hamburger/> */}
          <Header> </Header>
        {/* </header> */}
        <SessionProvider session={session}>
        <main>  {children}</main>
        </SessionProvider>
        <Footer />
        <Toaster  position="bottom-center"
  />
      </body>
    </html>
  );
}
